### ISSUE TITLE
Test selector is not working in angular projects.

### ISSUE THREAD

**Issue by SunilManthenaG01** [davidcalhoun/eslint-plugin-test-selectors#10]
Hi, 
I am trying to add this plugin to the angular project (v12). Not successfull as of now.
I extended both angular HTML rule and test selector rule angular rules are working but not the test-selector rules.

In my .eslintrc.json file I added the plugin as recommended by the documentation.

![image](https://user-images.githubusercontent.com/53482186/133818258-2970036f-1af7-4537-b962-e423b5f4e878.png)

Here is my html 
![image](https://user-images.githubusercontent.com/53482186/133818376-2c50c358-bbea-4623-a57c-d23c6d153a78.png)

when I run ng lint I am not getting the lint error.

![image](https://user-images.githubusercontent.com/53482186/133818473-20b5255c-e86b-463a-b8b1-75e78e34fe72.png)

Is there anything else I am missing here?

**Comment by SunilManthenaG01** [comment]
Hi, Can I get any help on this one, please?

**Comment by davidcalhoun** [comment]
Hi, thanks for the heads up!  I will try to look at this one soon.  Is it possible to provide a reduced test case of your setup?

**Comment by davidcalhoun** [comment]
Sorry for the delay - this plugin lints JSX only.  I'll update the readme to make this more clear.

**Comment by SunilManthenaG01** [comment]
@davidcalhoun  thank you for the update. Do you know any other plugin which can do the same thing on HTML?

**Comment by davidcalhoun** [comment]
@SunilManthenaG01 Apologies for the delay!  I'm not familiar with anything similar.  My instinct for your Angular project would be to take a look at how they check the HTML attributes in [angular-eslint](https://github.com/angular-eslint/angular-eslint) - you could probably follow the same pattern and write a custom rule!  E.g. take at the code for their `template-accessibility-alt-text` rule.
