### ISSUE TITLE
Allow data-testid

### ISSUE THREAD

**Issue by MFukazawa** [davidcalhoun/eslint-plugin-test-selectors#17]
## Issue
- Large codebase using `data-testid` rather than `data-test-id`
- Would like to use this plugin to enforce setting `data-testid`

## Request
- Be able to set `data-testid` as the target syntax in the settings of this plugin

**Comment by davidcalhoun** [comment]
Thanks for your interest.  You can achieve this now with the [testAttribute config](https://github.com/davidcalhoun/eslint-plugin-test-selectors#testattribute).

If you'd like to use `data-testid` for all rules, you can achieve it with something like this:

```
{
    rules: {
        'test-selectors/anchor': ['warn', 'always', { testAttribute: 'data-testid' }],
        'test-selectors/button': ['warn', 'always', { testAttribute: 'data-testid' }],
        'test-selectors/input': ['warn', 'always', { testAttribute: 'data-testid' }],
        'test-selectors/onChange': ['warn', 'always', { testAttribute: 'data-testid' }],
        'test-selectors/onClick': ['warn', 'always', { testAttribute: 'data-testid' }],
        'test-selectors/onKeyDown': ['warn', 'always', { testAttribute: 'data-testid' }],
        'test-selectors/onKeyUp': ['warn', 'always', { testAttribute: 'data-testid' }]
    }
}
```

**Comment by MFukazawa** [comment]
Thank you for the quick reply!!
