### ISSUE TITLE
Don't error for `readonly` or `disabled` by default

### ISSUE THREAD

**Issue by wesleytodd** [davidcalhoun/eslint-plugin-test-selectors#3]
I think it would be good to exclude elements with `readonly` or `disabled` by default with the ability to turn it on.  I am using `input`'s for displaying some non-editable information and this lint rule set errors on them.  One other option would be to not error on `input` without an `onChange`, but I am not sure which would be better and more robust.

**Comment by davidcalhoun** [comment]
Great suggestion, thanks!  For your second option, it may in any case be useful to support this.  I think I forgot to capture your feedback previously about warnings vs errors, which might help this.  Created a ticket to track it: https://github.com/davidcalhoun/eslint-plugin-test-selectors/issues/4

**Comment by wesleytodd** [comment]
Yeah I ended up just disabling it on all but the main files.  Even then I ended up disabling the entire anchor rule and about 10% of the other button and input cases.

**Comment by davidcalhoun** [comment]
Added in `1.1.0`:

* elements with `disabled` and `readonly` are now ignored by default (they can be turned back on in each rule's config - see the [readme](https://github.com/davidcalhoun/eslint-plugin-test-selectors#custom-rule-options))
* `plugin:test-selectors/recommended` now emits warnings by default.  For the old behavior which emits errors, folks can use `plugin:test-selectors/recommendedWithErrors`
