### ISSUE TITLE
Bug with testAttribute error messages

### ISSUE THREAD

**Issue by mahammedzkhan** [davidcalhoun/eslint-plugin-test-selectors#7]
I've added this plugin to our projects with the following settings:
```
rules: [
"test-selectors/onChange": [
      "warn",
      "always",
      {
        "testAttribute": "data-testid"
      }
    ],
]
```

Is it possible to set the `testAttribute` for all rules? Because I don't think there's a scenario where you use a different `testAttribute` for `onChange` and for `button`.

**Comment by davidcalhoun** [comment]
Thank you for the heads up and the details!

I believe I had the error message hard-coded before I added the configurable `testAttribute`, so it looks like I forgot to update a few places in the code.  I'll have a look.

**Comment by davidcalhoun** [comment]
Hello @mahammedzkhan - it looks like you just enabled that custom test selector for the `onChange` handler rule.  There's currently no way to turn on that custom selector for all rules unfortunately.  If you want to enable that custom attribute for all rules, your ESLint config will look something like this:

```json
{
    "rules": {
        "test-selectors/anchor": ["warn", "always", { "testAttribute": "data-testid" }],
        "test-selectors/button": ["warn", "always", { "testAttribute": "data-testid" }],
        "test-selectors/input": ["warn", "always", { "testAttribute": "data-testid" }],
        "test-selectors/onChange": ["warn", "always", { "testAttribute": "data-testid" }],
        "test-selectors/onClick": ["warn", "always", { "testAttribute": "data-testid" }],
        "test-selectors/onKeyDown": ["warn", "always", { "testAttribute": "data-testid" }],
        "test-selectors/onKeyUp": ["warn", "always", { "testAttribute": "data-testid" }]
    }
}
```
